[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "codebook" ]

[[language]]
name = "cpp"
language-servers = [ "clangd", "codebook" ]

[[language]]
name = "python"
language-servers = ["ty", "ruff", "jedi", "pylsp", "codebook" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "markdown-oxide", "codebook" ]
